### ISSUE TITLE
std::exception

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [KennyProgrammer/Force#1]
![image](https://user-images.githubusercontent.com/61359286/198885678-37c8c244-8e89-4267-bc07-f0e11ff9a12e.png)
When starting engine from directly Zip, without unzipping

After checking:
Same happens after unzipping.

Force version: 0.3.5 from Releases (https://github.com/KennyProgrammer/Force/releases/tag/v0.3.5)

**Comment by KennyProgrammer** [comment]
Thanks for reporting. Soon when 0.3.9 is out, i literally fixed ton of this little bugs, and upload new release.

**Comment by MrMasrozYTLIVE** [comment]
> 

Это была другая папка на жестком диске E созданная моим пользователем, так что там не должно было быть никаких прав администратора

**Comment by KennyProgrammer** [comment]
Ну смотри вот я открываю эту версию даже с архива и у меня она работает нормально.

![image](https://user-images.githubusercontent.com/56895345/200826413-71485da5-1a73-44a3-9e1b-93fd0e6b3a41.png)

![image](https://user-images.githubusercontent.com/56895345/200827587-a38983bb-3102-4b4b-9160-dec42389a0ea.png)

![image](https://user-images.githubusercontent.com/56895345/200827765-619e6c82-1bde-4207-bd3b-42463104c92f.png)

Вообще эта версия уже довольно старая, так как я давно работаю над новой, которую скоро выпушу. Поэтому сейчас довольно тяжело сказать что именно вызывает этот кряш.

Можешь попробовать запустить новую версию которая как раз скоро выйдет, интересно будет ли она у тебя запускаться.

https://drive.google.com/file/d/1LPTqiS1aguSI0VNu_5Wpb2I8P69wHpbX/view?usp=sharing

**Comment by MrMasrozYTLIVE** [comment]
Из архива не запустилось, крашнуло. НО! Зато ошибся теперь хотя бы нормальная

**Comment by MrMasrozYTLIVE** [comment]
![image](https://user-images.githubusercontent.com/61359286/200900523-cb802bf2-9756-44a3-8264-08e759ae568a.png)

**Comment by MrMasrozYTLIVE** [comment]
Скорее всего это приколы с моим пк, ведь у меня тут очень много разной херни

**Comment by KennyProgrammer** [comment]
Я конечно не уверен но может проблема в том что ты запускаешь на E а не на С? Никогда не запускал на E диске

**Comment by KennyProgrammer** [comment]
Попробуй запустить его на диске C

**Comment by KennyProgrammer** [comment]
![image](https://user-images.githubusercontent.com/56895345/200905316-e0e02bae-eedb-4595-8e3b-dd95f2ef7586.png)

**Comment by KennyProgrammer** [comment]
Так же на всякий случай чтобы писать скрипты и чтобы Force мог их компилировать тебе нужна Visual Studio 2019.

**Comment by KennyProgrammer** [comment]
Вообщем пиши мне на почту (kennytuts@gmail.com), когда проблема решиться я просто закрою этот вопрос с решением.

**Comment by KennyProgrammer** [comment]
In general problem was that user cannot have name of the user in Russian letters. Im already fix that issue, i guess.
