### ISSUE TITLE
Привет!

### ISSUE THREAD

**Issue by SuchDIFFERENT** [KennyProgrammer/Force#10]
Привет! Я тим лид Metacraft MMO - мы создаем свою онлайн-игру на java. Нам очень понравилось то, что ты делаешь и мы как раз ищем себе в команду человека, умеющего работать с графикой. Скажи, пожалуйста, можешь ли мы пообщаться с тобой? Если интересно - напиши, пожалуйста, сюда TG: @aqosticos

**Comment by KennyProgrammer** [comment]
Привет. Мне очень нравиться что вы делаете, ноо, у меня есть свой проект который занимает колосальное количество времени. Да и к тому же на Java уже не писал как года 3, т.к пишу на C++/C#.

Если нужна будет взаимная помощь напишу в будущем.
